CREATE  TABLE `iseer`.`users` (
  `ID` INT(20) NOT NULL AUTO_INCREMENT ,
  `NAME` VARCHAR(255) NOT NULL ,
  `GENDER` INT(2) NULL ,
  `MAIL` VARCHAR(45) NOT NULL ,
  `DESC` VARCHAR(255) NULL ,
  `LOCATION` VARCHAR(45) NULL ,
  `BIRTHDAY` DATE NULL ,
  `CREATE_TIME` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `id_UNIQUE` (`ID` ASC) );